// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: jsonschema.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginAdditionalProperties int32

const (
	PluginAdditionalProperties_DefaultAdditionalProperties PluginAdditionalProperties = 0
	// always_true: all messages to have additional_properties set to true
	PluginAdditionalProperties_AlwaysTrue PluginAdditionalProperties = 1
	// always_false: all messages to have additional_properties set to false
	PluginAdditionalProperties_AlwaysFalse PluginAdditionalProperties = 2
	// default_true: all messages will have additional_properties set to true if not defined
	PluginAdditionalProperties_DefaultTrue PluginAdditionalProperties = 3
	// default_false: all messages will have additional_properties set to false if not defined
	PluginAdditionalProperties_DefaultFalse PluginAdditionalProperties = 4
	// do_nothing: do not set additional_properties default value
	PluginAdditionalProperties_DoNothing PluginAdditionalProperties = 5
)

// Enum value maps for PluginAdditionalProperties.
var (
	PluginAdditionalProperties_name = map[int32]string{
		0: "DefaultAdditionalProperties",
		1: "AlwaysTrue",
		2: "AlwaysFalse",
		3: "DefaultTrue",
		4: "DefaultFalse",
		5: "DoNothing",
	}
	PluginAdditionalProperties_value = map[string]int32{
		"DefaultAdditionalProperties": 0,
		"AlwaysTrue":                  1,
		"AlwaysFalse":                 2,
		"DefaultTrue":                 3,
		"DefaultFalse":                4,
		"DoNothing":                   5,
	}
)

func (x PluginAdditionalProperties) Enum() *PluginAdditionalProperties {
	p := new(PluginAdditionalProperties)
	*p = x
	return p
}

func (x PluginAdditionalProperties) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginAdditionalProperties) Descriptor() protoreflect.EnumDescriptor {
	return file_jsonschema_proto_enumTypes[0].Descriptor()
}

func (PluginAdditionalProperties) Type() protoreflect.EnumType {
	return &file_jsonschema_proto_enumTypes[0]
}

func (x PluginAdditionalProperties) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginAdditionalProperties.Descriptor instead.
func (PluginAdditionalProperties) EnumDescriptor() ([]byte, []int) {
	return file_jsonschema_proto_rawDescGZIP(), []int{0}
}

type Draft int32

const (
	Draft_DraftDefault Draft = 0
	Draft_Draft04      Draft = 1
	Draft_Draft05      Draft = 2
	Draft_Draft06      Draft = 3
	Draft_Draft07      Draft = 4
	Draft_Draft201909  Draft = 5
	Draft_Draft202012  Draft = 6
)

// Enum value maps for Draft.
var (
	Draft_name = map[int32]string{
		0: "DraftDefault",
		1: "Draft04",
		2: "Draft05",
		3: "Draft06",
		4: "Draft07",
		5: "Draft201909",
		6: "Draft202012",
	}
	Draft_value = map[string]int32{
		"DraftDefault": 0,
		"Draft04":      1,
		"Draft05":      2,
		"Draft06":      3,
		"Draft07":      4,
		"Draft201909":  5,
		"Draft202012":  6,
	}
)

func (x Draft) Enum() *Draft {
	p := new(Draft)
	*p = x
	return p
}

func (x Draft) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Draft) Descriptor() protoreflect.EnumDescriptor {
	return file_jsonschema_proto_enumTypes[1].Descriptor()
}

func (Draft) Type() protoreflect.EnumType {
	return &file_jsonschema_proto_enumTypes[1]
}

func (x Draft) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Draft.Descriptor instead.
func (Draft) EnumDescriptor() ([]byte, []int) {
	return file_jsonschema_proto_rawDescGZIP(), []int{1}
}

type EnumOptions_MappingType int32

const (
	EnumOptions_MapToString EnumOptions_MappingType = 0
	EnumOptions_MapToNumber EnumOptions_MappingType = 1
	EnumOptions_MapToCustom EnumOptions_MappingType = 2
)

// Enum value maps for EnumOptions_MappingType.
var (
	EnumOptions_MappingType_name = map[int32]string{
		0: "MapToString",
		1: "MapToNumber",
		2: "MapToCustom",
	}
	EnumOptions_MappingType_value = map[string]int32{
		"MapToString": 0,
		"MapToNumber": 1,
		"MapToCustom": 2,
	}
)

func (x EnumOptions_MappingType) Enum() *EnumOptions_MappingType {
	p := new(EnumOptions_MappingType)
	*p = x
	return p
}

func (x EnumOptions_MappingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumOptions_MappingType) Descriptor() protoreflect.EnumDescriptor {
	return file_jsonschema_proto_enumTypes[2].Descriptor()
}

func (EnumOptions_MappingType) Type() protoreflect.EnumType {
	return &file_jsonschema_proto_enumTypes[2]
}

func (x EnumOptions_MappingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumOptions_MappingType.Descriptor instead.
func (EnumOptions_MappingType) EnumDescriptor() ([]byte, []int) {
	return file_jsonschema_proto_rawDescGZIP(), []int{8, 0}
}

// Not extendable, just define structure
// Plugin wide options
type PluginOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// WIP: visibility_level is used to determine which message should be generated.
	// Currently not work.
	VisibilityLevel uint32 `protobuf:"varint,1,opt,name=visibility_level,json=visibilityLevel,proto3" json:"visibility_level,omitempty"`
	// *
	// entrypoint_message is used which message should be entrypoint object of schema.
	//
	// default: null or empty
	// example:
	// - --jsonschema_opt=entrypoint_message=MyMessage
	EntrypointMessage string `protobuf:"bytes,2,opt,name=entrypoint_message,json=entrypointMessage,proto3" json:"entrypoint_message,omitempty"`
	// *
	// output_file_suffix is used to determine output file name suffix.
	// Values should end with '.json' or '.yaml' or '.yml'.
	//
	// default: .schema.json
	// example:
	// - --jsonschema_opt=output_file_suffix=.schema.json
	// - --jsonschema_opt=output_file_suffix=.schema.yaml
	OutputFileSuffix string `protobuf:"bytes,10,opt,name=output_file_suffix,json=outputFileSuffix,proto3" json:"output_file_suffix,omitempty"`
	// *
	// pretty_json_output is used to determine output json should be pretty printed.
	// This option is only used when output_file_suffix is '.json'.
	//
	// default: true
	// example:
	// - --jsonschema_opt=pretty_json_output=true
	// - --jsonschema_opt=pretty_json_output=false
	PrettyJsonOutput bool `protobuf:"varint,11,opt,name=pretty_json_output,json=prettyJsonOutput,proto3" json:"pretty_json_output,omitempty"`
	// *
	// draft is used to determine which draft version should be used.
	// The value should be one of Draft04, Draft05, Draft06, Draft07, Draft201909, Draft202012.
	//
	// default: Draft202012
	// example:
	// - --jsonschema_opt=draft=Draft202012
	Draft Draft `protobuf:"varint,12,opt,name=draft,proto3,enum=pubg.jsonschema.Draft" json:"draft,omitempty"`
	// *
	// mandatory_nullable determines whether this plugin should treat optional field as nullable.
	// Many programming languages do not differentiate between undefined and null.
	// However, scripting languages like JavaScript and TypeScript can distinguish between them.
	// By default, optional field is treated as nullable and undefined.
	//
	// default: false
	// example:
	// - --jsonschema_opt=mandatory_nullable=true
	// - --jsonschema_opt=mandatory_nullable=false
	MandatoryNullable bool `protobuf:"varint,13,opt,name=mandatory_nullable,json=mandatoryNullable,proto3" json:"mandatory_nullable,omitempty"`
	// *
	// int64_as_string determines whether int64 field treat as string.
	// Depends on Javascript specification, The JS stores integer to only 53bits.
	// So, if you want to use int64 field in JS, you should use string type.
	// References:
	//
	// default: false
	// example:
	// - --jsonschema_opt=int64_as_string=true
	// - --jsonschema_opt=int64_as_string=false
	Int64AsString bool `protobuf:"varint,14,opt,name=int64_as_string,json=int64AsString,proto3" json:"int64_as_string,omitempty"`
	// *
	// preserve_proto_field_names is used to determine if output json field names
	// should be identical to the proto field names.
	// Otherwise field names either use the value of the `json_name` field option
	// or they are automatically converted to lowerCamelCase.
	// This default behaviour mirrors the behaviour of Protobuf's canonical JSON format (ProtoJSON).
	//
	// default: false
	// example:
	// - --jsonschema_opt=preserve_proto_field_names=true
	// - --jsonschema_opt=preserve_proto_field_names=false
	PreserveProtoFieldNames bool `protobuf:"varint,15,opt,name=preserve_proto_field_names,json=preserveProtoFieldNames,proto3" json:"preserve_proto_field_names,omitempty"`
	// *
	// additional_properties option can controls all message's additional_properties property.
	// If you want set additional properties for all messages, use always_true or always_false.
	// If you want to set additional properties for not defined messages, use default_true or default_false.
	//
	// default: 'DoNothing'
	// example:
	// - --jsonschema_opt=additional_properties=AlwaysTrue
	// - --jsonschema_opt=additional_properties=AlwaysFalse
	// - --jsonschema_opt=additional_properties=DefaultTrue
	// - --jsonschema_opt=additional_properties=DefaultFalse
	// - --jsonschema_opt=additional_properties=DoNothing
	AdditionalProperties PluginAdditionalProperties `protobuf:"varint,16,opt,name=additional_properties,json=additionalProperties,proto3,enum=pubg.jsonschema.PluginAdditionalProperties" json:"additional_properties,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PluginOptions) Reset() {
	*x = PluginOptions{}
	mi := &file_jsonschema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginOptions) ProtoMessage() {}

func (x *PluginOptions) ProtoReflect() protoreflect.Message {
	mi := &file_jsonschema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginOptions.ProtoReflect.Descriptor instead.
func (*PluginOptions) Descriptor() ([]byte, []int) {
	return file_jsonschema_proto_rawDescGZIP(), []int{0}
}

func (x *PluginOptions) GetVisibilityLevel() uint32 {
	if x != nil {
		return x.VisibilityLevel
	}
	return 0
}

func (x *PluginOptions) GetEntrypointMessage() string {
	if x != nil {
		return x.EntrypointMessage
	}
	return ""
}

func (x *PluginOptions) GetOutputFileSuffix() string {
	if x != nil {
		return x.OutputFileSuffix
	}
	return ""
}

func (x *PluginOptions) GetPrettyJsonOutput() bool {
	if x != nil {
		return x.PrettyJsonOutput
	}
	return false
}

func (x *PluginOptions) GetDraft() Draft {
	if x != nil {
		return x.Draft
	}
	return Draft_DraftDefault
}

func (x *PluginOptions) GetMandatoryNullable() bool {
	if x != nil {
		return x.MandatoryNullable
	}
	return false
}

func (x *PluginOptions) GetInt64AsString() bool {
	if x != nil {
		return x.Int64AsString
	}
	return false
}

func (x *PluginOptions) GetPreserveProtoFieldNames() bool {
	if x != nil {
		return x.PreserveProtoFieldNames
	}
	return false
}

func (x *PluginOptions) GetAdditionalProperties() PluginAdditionalProperties {
	if x != nil {
		return x.AdditionalProperties
	}
	return PluginAdditionalProperties_DefaultAdditionalProperties
}

type FileOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// WIP: visibility_level is used to determine which message should be generated.
	// Currently not work.
	VisibilityLevel uint32 `protobuf:"varint,1,opt,name=visibility_level,json=visibilityLevel,proto3" json:"visibility_level,omitempty"`
	// *
	// entrypoint_message is used which message should be entrypoint object of schema.
	// default: inherit from PluginOptions.entrypoint_message
	EntrypointMessage string `protobuf:"bytes,2,opt,name=entrypoint_message,json=entrypointMessage,proto3" json:"entrypoint_message,omitempty"`
	Title             string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description       string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_jsonschema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_jsonschema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptions.ProtoReflect.Descriptor instead.
func (*FileOptions) Descriptor() ([]byte, []int) {
	return file_jsonschema_proto_rawDescGZIP(), []int{1}
}

func (x *FileOptions) GetVisibilityLevel() uint32 {
	if x != nil {
		return x.VisibilityLevel
	}
	return 0
}

func (x *FileOptions) GetEntrypointMessage() string {
	if x != nil {
		return x.EntrypointMessage
	}
	return ""
}

func (x *FileOptions) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FileOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type MessageOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// WIP: visibility_level is used to determine which message should be generated.
	// Currently not work.
	VisibilityLevel uint32          `protobuf:"varint,1,opt,name=visibility_level,json=visibilityLevel,proto3" json:"visibility_level,omitempty"`
	Title           string          `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string          `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Object          *ObjectKeywords `protobuf:"bytes,10,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_jsonschema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_jsonschema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_jsonschema_proto_rawDescGZIP(), []int{2}
}

func (x *MessageOptions) GetVisibilityLevel() uint32 {
	if x != nil {
		return x.VisibilityLevel
	}
	return 0
}

func (x *MessageOptions) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MessageOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MessageOptions) GetObject() *ObjectKeywords {
	if x != nil {
		return x.Object
	}
	return nil
}

type ObjectKeywords struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AdditionalProperties *bool                  `protobuf:"varint,1,opt,name=additional_properties,json=additionalProperties,proto3,oneof" json:"additional_properties,omitempty"`
	// repeated JsonSchema additional_properties = 10;
	MinProperties *uint32 `protobuf:"varint,2,opt,name=min_properties,json=minProperties,proto3,oneof" json:"min_properties,omitempty"`
	MaxProperties *uint32 `protobuf:"varint,3,opt,name=max_properties,json=maxProperties,proto3,oneof" json:"max_properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectKeywords) Reset() {
	*x = ObjectKeywords{}
	mi := &file_jsonschema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectKeywords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectKeywords) ProtoMessage() {}

func (x *ObjectKeywords) ProtoReflect() protoreflect.Message {
	mi := &file_jsonschema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectKeywords.ProtoReflect.Descriptor instead.
func (*ObjectKeywords) Descriptor() ([]byte, []int) {
	return file_jsonschema_proto_rawDescGZIP(), []int{3}
}

func (x *ObjectKeywords) GetAdditionalProperties() bool {
	if x != nil && x.AdditionalProperties != nil {
		return *x.AdditionalProperties
	}
	return false
}

func (x *ObjectKeywords) GetMinProperties() uint32 {
	if x != nil && x.MinProperties != nil {
		return *x.MinProperties
	}
	return 0
}

func (x *ObjectKeywords) GetMaxProperties() uint32 {
	if x != nil && x.MaxProperties != nil {
		return *x.MaxProperties
	}
	return 0
}

type FieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// WIP: visibility_level is used to determine which message should be generated.
	// Currently not work.
	VisibilityLevel uint32           `protobuf:"varint,1,opt,name=visibility_level,json=visibilityLevel,proto3" json:"visibility_level,omitempty"`
	Title           string           `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string           `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Nullable        bool             `protobuf:"varint,5,opt,name=nullable,proto3" json:"nullable,omitempty"`
	Default         *anypb.Any       `protobuf:"bytes,10,opt,name=default,proto3" json:"default,omitempty"`
	Array           *ArrayKeywords   `protobuf:"bytes,11,opt,name=array,proto3" json:"array,omitempty"`
	Numeric         *NumericKeywords `protobuf:"bytes,12,opt,name=numeric,proto3" json:"numeric,omitempty"`
	String_         *StringKeywords  `protobuf:"bytes,13,opt,name=string,proto3" json:"string,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_jsonschema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_jsonschema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_jsonschema_proto_rawDescGZIP(), []int{4}
}

func (x *FieldOptions) GetVisibilityLevel() uint32 {
	if x != nil {
		return x.VisibilityLevel
	}
	return 0
}

func (x *FieldOptions) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FieldOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FieldOptions) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *FieldOptions) GetDefault() *anypb.Any {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *FieldOptions) GetArray() *ArrayKeywords {
	if x != nil {
		return x.Array
	}
	return nil
}

func (x *FieldOptions) GetNumeric() *NumericKeywords {
	if x != nil {
		return x.Numeric
	}
	return nil
}

func (x *FieldOptions) GetString_() *StringKeywords {
	if x != nil {
		return x.String_
	}
	return nil
}

type ArrayKeywords struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinItems      *uint32                `protobuf:"varint,1,opt,name=min_items,json=minItems,proto3,oneof" json:"min_items,omitempty"`
	MaxItems      *uint32                `protobuf:"varint,2,opt,name=max_items,json=maxItems,proto3,oneof" json:"max_items,omitempty"`
	UniqueItems   *bool                  `protobuf:"varint,3,opt,name=unique_items,json=uniqueItems,proto3,oneof" json:"unique_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayKeywords) Reset() {
	*x = ArrayKeywords{}
	mi := &file_jsonschema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayKeywords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayKeywords) ProtoMessage() {}

func (x *ArrayKeywords) ProtoReflect() protoreflect.Message {
	mi := &file_jsonschema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayKeywords.ProtoReflect.Descriptor instead.
func (*ArrayKeywords) Descriptor() ([]byte, []int) {
	return file_jsonschema_proto_rawDescGZIP(), []int{5}
}

func (x *ArrayKeywords) GetMinItems() uint32 {
	if x != nil && x.MinItems != nil {
		return *x.MinItems
	}
	return 0
}

func (x *ArrayKeywords) GetMaxItems() uint32 {
	if x != nil && x.MaxItems != nil {
		return *x.MaxItems
	}
	return 0
}

func (x *ArrayKeywords) GetUniqueItems() bool {
	if x != nil && x.UniqueItems != nil {
		return *x.UniqueItems
	}
	return false
}

type NumericKeywords struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Min:
	//
	//	*NumericKeywords_InclusiveMinimum
	//	*NumericKeywords_ExclusiveMinimum
	Min isNumericKeywords_Min `protobuf_oneof:"min"`
	// Types that are valid to be assigned to Max:
	//
	//	*NumericKeywords_InclusiveMaximum
	//	*NumericKeywords_ExclusiveMaximum
	Max           isNumericKeywords_Max `protobuf_oneof:"max"`
	MultipleOf    *int32                `protobuf:"varint,5,opt,name=multiple_of,json=multipleOf,proto3,oneof" json:"multiple_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumericKeywords) Reset() {
	*x = NumericKeywords{}
	mi := &file_jsonschema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericKeywords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericKeywords) ProtoMessage() {}

func (x *NumericKeywords) ProtoReflect() protoreflect.Message {
	mi := &file_jsonschema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericKeywords.ProtoReflect.Descriptor instead.
func (*NumericKeywords) Descriptor() ([]byte, []int) {
	return file_jsonschema_proto_rawDescGZIP(), []int{6}
}

func (x *NumericKeywords) GetMin() isNumericKeywords_Min {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *NumericKeywords) GetInclusiveMinimum() float64 {
	if x != nil {
		if x, ok := x.Min.(*NumericKeywords_InclusiveMinimum); ok {
			return x.InclusiveMinimum
		}
	}
	return 0
}

func (x *NumericKeywords) GetExclusiveMinimum() float64 {
	if x != nil {
		if x, ok := x.Min.(*NumericKeywords_ExclusiveMinimum); ok {
			return x.ExclusiveMinimum
		}
	}
	return 0
}

func (x *NumericKeywords) GetMax() isNumericKeywords_Max {
	if x != nil {
		return x.Max
	}
	return nil
}

func (x *NumericKeywords) GetInclusiveMaximum() float64 {
	if x != nil {
		if x, ok := x.Max.(*NumericKeywords_InclusiveMaximum); ok {
			return x.InclusiveMaximum
		}
	}
	return 0
}

func (x *NumericKeywords) GetExclusiveMaximum() float64 {
	if x != nil {
		if x, ok := x.Max.(*NumericKeywords_ExclusiveMaximum); ok {
			return x.ExclusiveMaximum
		}
	}
	return 0
}

func (x *NumericKeywords) GetMultipleOf() int32 {
	if x != nil && x.MultipleOf != nil {
		return *x.MultipleOf
	}
	return 0
}

type isNumericKeywords_Min interface {
	isNumericKeywords_Min()
}

type NumericKeywords_InclusiveMinimum struct {
	InclusiveMinimum float64 `protobuf:"fixed64,1,opt,name=inclusive_minimum,json=inclusiveMinimum,proto3,oneof"`
}

type NumericKeywords_ExclusiveMinimum struct {
	ExclusiveMinimum float64 `protobuf:"fixed64,3,opt,name=exclusive_minimum,json=exclusiveMinimum,proto3,oneof"`
}

func (*NumericKeywords_InclusiveMinimum) isNumericKeywords_Min() {}

func (*NumericKeywords_ExclusiveMinimum) isNumericKeywords_Min() {}

type isNumericKeywords_Max interface {
	isNumericKeywords_Max()
}

type NumericKeywords_InclusiveMaximum struct {
	InclusiveMaximum float64 `protobuf:"fixed64,2,opt,name=inclusive_maximum,json=inclusiveMaximum,proto3,oneof"`
}

type NumericKeywords_ExclusiveMaximum struct {
	ExclusiveMaximum float64 `protobuf:"fixed64,4,opt,name=exclusive_maximum,json=exclusiveMaximum,proto3,oneof"`
}

func (*NumericKeywords_InclusiveMaximum) isNumericKeywords_Max() {}

func (*NumericKeywords_ExclusiveMaximum) isNumericKeywords_Max() {}

type StringKeywords struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLength     *uint32                `protobuf:"varint,1,opt,name=min_length,json=minLength,proto3,oneof" json:"min_length,omitempty"`
	MaxLength     *uint32                `protobuf:"varint,2,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`
	Pattern       string                 `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringKeywords) Reset() {
	*x = StringKeywords{}
	mi := &file_jsonschema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringKeywords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringKeywords) ProtoMessage() {}

func (x *StringKeywords) ProtoReflect() protoreflect.Message {
	mi := &file_jsonschema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringKeywords.ProtoReflect.Descriptor instead.
func (*StringKeywords) Descriptor() ([]byte, []int) {
	return file_jsonschema_proto_rawDescGZIP(), []int{7}
}

func (x *StringKeywords) GetMinLength() uint32 {
	if x != nil && x.MinLength != nil {
		return *x.MinLength
	}
	return 0
}

func (x *StringKeywords) GetMaxLength() uint32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

func (x *StringKeywords) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *StringKeywords) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type EnumOptions struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	MappingType   EnumOptions_MappingType `protobuf:"varint,1,opt,name=mapping_type,json=mappingType,proto3,enum=pubg.jsonschema.EnumOptions_MappingType" json:"mapping_type,omitempty"`
	Title         string                  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumOptions) Reset() {
	*x = EnumOptions{}
	mi := &file_jsonschema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumOptions) ProtoMessage() {}

func (x *EnumOptions) ProtoReflect() protoreflect.Message {
	mi := &file_jsonschema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumOptions.ProtoReflect.Descriptor instead.
func (*EnumOptions) Descriptor() ([]byte, []int) {
	return file_jsonschema_proto_rawDescGZIP(), []int{8}
}

func (x *EnumOptions) GetMappingType() EnumOptions_MappingType {
	if x != nil {
		return x.MappingType
	}
	return EnumOptions_MapToString
}

func (x *EnumOptions) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EnumOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type EnumValueOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomValue   *anypb.Any             `protobuf:"bytes,10,opt,name=custom_value,json=customValue,proto3" json:"custom_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValueOptions) Reset() {
	*x = EnumValueOptions{}
	mi := &file_jsonschema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValueOptions) ProtoMessage() {}

func (x *EnumValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_jsonschema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValueOptions.ProtoReflect.Descriptor instead.
func (*EnumValueOptions) Descriptor() ([]byte, []int) {
	return file_jsonschema_proto_rawDescGZIP(), []int{9}
}

func (x *EnumValueOptions) GetCustomValue() *anypb.Any {
	if x != nil {
		return x.CustomValue
	}
	return nil
}

var file_jsonschema_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*FileOptions)(nil),
		Field:         11341,
		Name:          "pubg.jsonschema.file",
		Tag:           "bytes,11341,opt,name=file",
		Filename:      "jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         11342,
		Name:          "pubg.jsonschema.message",
		Tag:           "bytes,11342,opt,name=message",
		Filename:      "jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         11343,
		Name:          "pubg.jsonschema.field",
		Tag:           "bytes,11343,opt,name=field",
		Filename:      "jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*EnumOptions)(nil),
		Field:         11344,
		Name:          "pubg.jsonschema.enum",
		Tag:           "bytes,11344,opt,name=enum",
		Filename:      "jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*EnumValueOptions)(nil),
		Field:         11345,
		Name:          "pubg.jsonschema.enum_value",
		Tag:           "bytes,11345,opt,name=enum_value",
		Filename:      "jsonschema.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional pubg.jsonschema.FileOptions file = 11341;
	E_File = &file_jsonschema_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional pubg.jsonschema.MessageOptions message = 11342;
	E_Message = &file_jsonschema_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional pubg.jsonschema.FieldOptions field = 11343;
	E_Field = &file_jsonschema_proto_extTypes[2]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional pubg.jsonschema.EnumOptions enum = 11344;
	E_Enum = &file_jsonschema_proto_extTypes[3]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional pubg.jsonschema.EnumValueOptions enum_value = 11345;
	E_EnumValue = &file_jsonschema_proto_extTypes[4]
)

var File_jsonschema_proto protoreflect.FileDescriptor

const file_jsonschema_proto_rawDesc = "" +
	"\n" +
	"\x10jsonschema.proto\x12\x0fpubg.jsonschema\x1a google/protobuf/descriptor.proto\x1a\x19google/protobuf/any.proto\"\xe9\x03\n" +
	"\rPluginOptions\x12)\n" +
	"\x10visibility_level\x18\x01 \x01(\rR\x0fvisibilityLevel\x12-\n" +
	"\x12entrypoint_message\x18\x02 \x01(\tR\x11entrypointMessage\x12,\n" +
	"\x12output_file_suffix\x18\n" +
	" \x01(\tR\x10outputFileSuffix\x12,\n" +
	"\x12pretty_json_output\x18\v \x01(\bR\x10prettyJsonOutput\x12,\n" +
	"\x05draft\x18\f \x01(\x0e2\x16.pubg.jsonschema.DraftR\x05draft\x12-\n" +
	"\x12mandatory_nullable\x18\r \x01(\bR\x11mandatoryNullable\x12&\n" +
	"\x0fint64_as_string\x18\x0e \x01(\bR\rint64AsString\x12;\n" +
	"\x1apreserve_proto_field_names\x18\x0f \x01(\bR\x17preserveProtoFieldNames\x12`\n" +
	"\x15additional_properties\x18\x10 \x01(\x0e2+.pubg.jsonschema.PluginAdditionalPropertiesR\x14additionalProperties\"\x9f\x01\n" +
	"\vFileOptions\x12)\n" +
	"\x10visibility_level\x18\x01 \x01(\rR\x0fvisibilityLevel\x12-\n" +
	"\x12entrypoint_message\x18\x02 \x01(\tR\x11entrypointMessage\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\xac\x01\n" +
	"\x0eMessageOptions\x12)\n" +
	"\x10visibility_level\x18\x01 \x01(\rR\x0fvisibilityLevel\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x127\n" +
	"\x06object\x18\n" +
	" \x01(\v2\x1f.pubg.jsonschema.ObjectKeywordsR\x06object\"\xe2\x01\n" +
	"\x0eObjectKeywords\x128\n" +
	"\x15additional_properties\x18\x01 \x01(\bH\x00R\x14additionalProperties\x88\x01\x01\x12*\n" +
	"\x0emin_properties\x18\x02 \x01(\rH\x01R\rminProperties\x88\x01\x01\x12*\n" +
	"\x0emax_properties\x18\x03 \x01(\rH\x02R\rmaxProperties\x88\x01\x01B\x18\n" +
	"\x16_additional_propertiesB\x11\n" +
	"\x0f_min_propertiesB\x11\n" +
	"\x0f_max_properties\"\xe8\x02\n" +
	"\fFieldOptions\x12)\n" +
	"\x10visibility_level\x18\x01 \x01(\rR\x0fvisibilityLevel\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bnullable\x18\x05 \x01(\bR\bnullable\x12.\n" +
	"\adefault\x18\n" +
	" \x01(\v2\x14.google.protobuf.AnyR\adefault\x124\n" +
	"\x05array\x18\v \x01(\v2\x1e.pubg.jsonschema.ArrayKeywordsR\x05array\x12:\n" +
	"\anumeric\x18\f \x01(\v2 .pubg.jsonschema.NumericKeywordsR\anumeric\x127\n" +
	"\x06string\x18\r \x01(\v2\x1f.pubg.jsonschema.StringKeywordsR\x06string\"\xa8\x01\n" +
	"\rArrayKeywords\x12 \n" +
	"\tmin_items\x18\x01 \x01(\rH\x00R\bminItems\x88\x01\x01\x12 \n" +
	"\tmax_items\x18\x02 \x01(\rH\x01R\bmaxItems\x88\x01\x01\x12&\n" +
	"\funique_items\x18\x03 \x01(\bH\x02R\vuniqueItems\x88\x01\x01B\f\n" +
	"\n" +
	"_min_itemsB\f\n" +
	"\n" +
	"_max_itemsB\x0f\n" +
	"\r_unique_items\"\x91\x02\n" +
	"\x0fNumericKeywords\x12-\n" +
	"\x11inclusive_minimum\x18\x01 \x01(\x01H\x00R\x10inclusiveMinimum\x12-\n" +
	"\x11exclusive_minimum\x18\x03 \x01(\x01H\x00R\x10exclusiveMinimum\x12-\n" +
	"\x11inclusive_maximum\x18\x02 \x01(\x01H\x01R\x10inclusiveMaximum\x12-\n" +
	"\x11exclusive_maximum\x18\x04 \x01(\x01H\x01R\x10exclusiveMaximum\x12$\n" +
	"\vmultiple_of\x18\x05 \x01(\x05H\x02R\n" +
	"multipleOf\x88\x01\x01B\x05\n" +
	"\x03minB\x05\n" +
	"\x03maxB\x0e\n" +
	"\f_multiple_of\"\xa8\x01\n" +
	"\x0eStringKeywords\x12\"\n" +
	"\n" +
	"min_length\x18\x01 \x01(\rH\x00R\tminLength\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_length\x18\x02 \x01(\rH\x01R\tmaxLength\x88\x01\x01\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06formatB\r\n" +
	"\v_min_lengthB\r\n" +
	"\v_max_length\"\xd4\x01\n" +
	"\vEnumOptions\x12K\n" +
	"\fmapping_type\x18\x01 \x01(\x0e2(.pubg.jsonschema.EnumOptions.MappingTypeR\vmappingType\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"@\n" +
	"\vMappingType\x12\x0f\n" +
	"\vMapToString\x10\x00\x12\x0f\n" +
	"\vMapToNumber\x10\x01\x12\x0f\n" +
	"\vMapToCustom\x10\x02\"K\n" +
	"\x10EnumValueOptions\x127\n" +
	"\fcustom_value\x18\n" +
	" \x01(\v2\x14.google.protobuf.AnyR\vcustomValue*\x90\x01\n" +
	"\x1aPluginAdditionalProperties\x12\x1f\n" +
	"\x1bDefaultAdditionalProperties\x10\x00\x12\x0e\n" +
	"\n" +
	"AlwaysTrue\x10\x01\x12\x0f\n" +
	"\vAlwaysFalse\x10\x02\x12\x0f\n" +
	"\vDefaultTrue\x10\x03\x12\x10\n" +
	"\fDefaultFalse\x10\x04\x12\r\n" +
	"\tDoNothing\x10\x05*o\n" +
	"\x05Draft\x12\x10\n" +
	"\fDraftDefault\x10\x00\x12\v\n" +
	"\aDraft04\x10\x01\x12\v\n" +
	"\aDraft05\x10\x02\x12\v\n" +
	"\aDraft06\x10\x03\x12\v\n" +
	"\aDraft07\x10\x04\x12\x0f\n" +
	"\vDraft201909\x10\x05\x12\x0f\n" +
	"\vDraft202012\x10\x06:O\n" +
	"\x04file\x12\x1c.google.protobuf.FileOptions\x18\xcdX \x01(\v2\x1c.pubg.jsonschema.FileOptionsR\x04file:[\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xceX \x01(\v2\x1f.pubg.jsonschema.MessageOptionsR\amessage:S\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xcfX \x01(\v2\x1d.pubg.jsonschema.FieldOptionsR\x05field:O\n" +
	"\x04enum\x12\x1c.google.protobuf.EnumOptions\x18\xd0X \x01(\v2\x1c.pubg.jsonschema.EnumOptionsR\x04enum:d\n" +
	"\n" +
	"enum_value\x12!.google.protobuf.EnumValueOptions\x18\xd1X \x01(\v2!.pubg.jsonschema.EnumValueOptionsR\tenumValueB1Z/github.com/pubg/protoc-gen-jsonschema/pkg/protob\x06proto3"

var (
	file_jsonschema_proto_rawDescOnce sync.Once
	file_jsonschema_proto_rawDescData []byte
)

func file_jsonschema_proto_rawDescGZIP() []byte {
	file_jsonschema_proto_rawDescOnce.Do(func() {
		file_jsonschema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jsonschema_proto_rawDesc), len(file_jsonschema_proto_rawDesc)))
	})
	return file_jsonschema_proto_rawDescData
}

var file_jsonschema_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_jsonschema_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_jsonschema_proto_goTypes = []any{
	(PluginAdditionalProperties)(0),       // 0: pubg.jsonschema.PluginAdditionalProperties
	(Draft)(0),                            // 1: pubg.jsonschema.Draft
	(EnumOptions_MappingType)(0),          // 2: pubg.jsonschema.EnumOptions.MappingType
	(*PluginOptions)(nil),                 // 3: pubg.jsonschema.PluginOptions
	(*FileOptions)(nil),                   // 4: pubg.jsonschema.FileOptions
	(*MessageOptions)(nil),                // 5: pubg.jsonschema.MessageOptions
	(*ObjectKeywords)(nil),                // 6: pubg.jsonschema.ObjectKeywords
	(*FieldOptions)(nil),                  // 7: pubg.jsonschema.FieldOptions
	(*ArrayKeywords)(nil),                 // 8: pubg.jsonschema.ArrayKeywords
	(*NumericKeywords)(nil),               // 9: pubg.jsonschema.NumericKeywords
	(*StringKeywords)(nil),                // 10: pubg.jsonschema.StringKeywords
	(*EnumOptions)(nil),                   // 11: pubg.jsonschema.EnumOptions
	(*EnumValueOptions)(nil),              // 12: pubg.jsonschema.EnumValueOptions
	(*anypb.Any)(nil),                     // 13: google.protobuf.Any
	(*descriptorpb.FileOptions)(nil),      // 14: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil),   // 15: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),     // 16: google.protobuf.FieldOptions
	(*descriptorpb.EnumOptions)(nil),      // 17: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 18: google.protobuf.EnumValueOptions
}
var file_jsonschema_proto_depIdxs = []int32{
	1,  // 0: pubg.jsonschema.PluginOptions.draft:type_name -> pubg.jsonschema.Draft
	0,  // 1: pubg.jsonschema.PluginOptions.additional_properties:type_name -> pubg.jsonschema.PluginAdditionalProperties
	6,  // 2: pubg.jsonschema.MessageOptions.object:type_name -> pubg.jsonschema.ObjectKeywords
	13, // 3: pubg.jsonschema.FieldOptions.default:type_name -> google.protobuf.Any
	8,  // 4: pubg.jsonschema.FieldOptions.array:type_name -> pubg.jsonschema.ArrayKeywords
	9,  // 5: pubg.jsonschema.FieldOptions.numeric:type_name -> pubg.jsonschema.NumericKeywords
	10, // 6: pubg.jsonschema.FieldOptions.string:type_name -> pubg.jsonschema.StringKeywords
	2,  // 7: pubg.jsonschema.EnumOptions.mapping_type:type_name -> pubg.jsonschema.EnumOptions.MappingType
	13, // 8: pubg.jsonschema.EnumValueOptions.custom_value:type_name -> google.protobuf.Any
	14, // 9: pubg.jsonschema.file:extendee -> google.protobuf.FileOptions
	15, // 10: pubg.jsonschema.message:extendee -> google.protobuf.MessageOptions
	16, // 11: pubg.jsonschema.field:extendee -> google.protobuf.FieldOptions
	17, // 12: pubg.jsonschema.enum:extendee -> google.protobuf.EnumOptions
	18, // 13: pubg.jsonschema.enum_value:extendee -> google.protobuf.EnumValueOptions
	4,  // 14: pubg.jsonschema.file:type_name -> pubg.jsonschema.FileOptions
	5,  // 15: pubg.jsonschema.message:type_name -> pubg.jsonschema.MessageOptions
	7,  // 16: pubg.jsonschema.field:type_name -> pubg.jsonschema.FieldOptions
	11, // 17: pubg.jsonschema.enum:type_name -> pubg.jsonschema.EnumOptions
	12, // 18: pubg.jsonschema.enum_value:type_name -> pubg.jsonschema.EnumValueOptions
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	14, // [14:19] is the sub-list for extension type_name
	9,  // [9:14] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_jsonschema_proto_init() }
func file_jsonschema_proto_init() {
	if File_jsonschema_proto != nil {
		return
	}
	file_jsonschema_proto_msgTypes[3].OneofWrappers = []any{}
	file_jsonschema_proto_msgTypes[5].OneofWrappers = []any{}
	file_jsonschema_proto_msgTypes[6].OneofWrappers = []any{
		(*NumericKeywords_InclusiveMinimum)(nil),
		(*NumericKeywords_ExclusiveMinimum)(nil),
		(*NumericKeywords_InclusiveMaximum)(nil),
		(*NumericKeywords_ExclusiveMaximum)(nil),
	}
	file_jsonschema_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jsonschema_proto_rawDesc), len(file_jsonschema_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_jsonschema_proto_goTypes,
		DependencyIndexes: file_jsonschema_proto_depIdxs,
		EnumInfos:         file_jsonschema_proto_enumTypes,
		MessageInfos:      file_jsonschema_proto_msgTypes,
		ExtensionInfos:    file_jsonschema_proto_extTypes,
	}.Build()
	File_jsonschema_proto = out.File
	file_jsonschema_proto_goTypes = nil
	file_jsonschema_proto_depIdxs = nil
}
